### ISSUE TITLE
Criar Banco de Dados

### ISSUE THREAD

**Issue by SherwoodArcher** [SherwoodArcher/IOTForm#1]
CREATE TABLE Cliente (
    Id INTEGER IDENTITY(0,1) NOT NULL,
    Nome NVARCHAR(100) NOT NULL,

    CONSTRAINT PkClienteId PRIMARY KEY(Id)
);

CREATE TABLE Questionario (
    Id INTEGER IDENTITY(0,1) NOT NULL,
    Questao NVARCHAR NOT NULL
    CONSTRAINT PkQuestionario PRIMARY KEY(Id)
);

CREATE TABLE QuestionarioRespostas(
    Id INTEGER IDENTITY(0,1) NOT NULL,
    IdCliente INTEGER NOT NULL,
    IdQuestao INTEGER NOT NULL,
    Resposta BINARY NULL,
    RespostaTexto NVARCHAR(1024) NULL,

    CONSTRAINT PkQuestionarioRespostas PRIMARY KEY(Id),
    CONSTRAINT FkQuestionario FOREIGN KEY(IdQuestao)
        REFERENCES Questionario(Id),
    CONSTRAINT FkQuestionarioCliente FOREIGN KEY(IdCliente)
        REFERENCES Cliente(Id)
);

CREATE TABLE AtivosDevices (
    Id INTEGER IDENTITY(0,1) NOT NULL,
    IdCliente INTEGER NOT NULL,
    GeralNumeroAtivos TINYINT NOT NULL,
    GeralValorAtivo TINYINT NOT NULL,
    GeralValorEconomico TINYINT NOT NULL,
    GeralComplexidadeAtivo TINYINT NOT NULL,
    GeralHeteroAtivo TINYINT NOT NULL,
    
    PoderLogicaNegocio TINYINT NOT NULL,
    PoderProcessamento TINYINT NOT NULL,
    PoderRequerimentos TINYINT NOT NULL,
    PoderGestaoLocal TINYINT NOT NULL,
    
    OutrosFonteEnergia TINYINT NOT NULL,
    OutrosAmbiente TINYINT NOT NULL,
    
    GestaoVidaUtil TINYINT NOT NULL,
    GestaoRestricoesHardware TINYINT NOT NULL,
    GestaoRestricoesSoftware TINYINT NOT NULL,
    
    CONSTRAINT PkAtivosDevices PRIMARY KEY(Id),
    CONSTRAINT FkAtivosDevices FOREIGN KEY(IdCliente)
        REFERENCES Cliente(Id)
);

CREATE TABLE ComunicacaoConectividade(
    Id INTEGER IDENTITY(0,1) NOT NULL,
    IdCliente INTEGER NOT NULL,
    LocalTecnologia TINYINT NOT NULL,
    LocalLarguraBanda TINYINT NOT NULL,
    LocalMaximaLatencia TINYINT NOT NULL,
    RemotaTecnologia TINYINT NOT NULL,
    RemotaLarguraBanda TINYINT NOT NULL,
    RemotaMaximaLatencia TINYINT NOT NULL,
    
    CONSTRAINT PkComunicacaoConectividade PRIMARY KEY(Id),
    CONSTRAINT FKComunicacaoConectividade FOREIGN KEY(IdCliente)
        REFERENCES Cliente(ID)
);

CREATE TABLE ServicosBackend(
    Id INTEGER IDENTITY(0,1) NOT NULL,
    IdCliente INTEGER NOT NULL,
    GeralEstrategiaAplicacao TINYINT NOT NULL,
    GeralComplexidadeNegocio TINYINT NOT NULL,
    GeralIntegracaoBackend TINYINT NOT NULL,
    GestaoVolumeDados TINYINT NOT NULL,
    GestaoVariedadeDados TINYINT NOT NULL,
    GestaoVariabilidadeDados TINYINT NOT NULL,
    GestaoAnalytics TINYINT NOT NULL,
    
    CONSTRAINT PkServicosBackend PRIMARY KEY(Id),
    CONSTRAINT FkServicosBackend FOREIGN KEY(IdCliente)
        REFERENCES Cliente(Id)
    
);

CREATE TABLE PadroesRequerimentos(
    Id INTEGER IDENTITY(0,1) NOT NULL,
    IdCliente INTEGER NOT NULL,
    RequerimentosRegiao TINYINT NOT NULL,
    RequerimentosIndustria TINYINT NOT NULL,
    RequerimentosTecnologia TINYINT NOT NULL,
    PadroesTecnicos TINYINT NOT NULL,
    PadroesFuncionais TINYINT NOT NULL,

    CONSTRAINT PkPadroesRequerimentos PRIMARY KEY(Id),
    CONSTRAINT FkPadroesRequerimentos FOREIGN KEY(IdCliente)
        REFERENCES Cliente(Id)
);

CREATE TABLE AmbienteProjeto(
    Id INTEGER IDENTITY(0,1) NOT NULL,
    IdCliente INTEGER NOT NULL,
    AmbienteTempo TINYINT NOT NULL,
    AmbienteBudget TINYINT NOT NULL,
    AmbienteFuncionais TINYINT NOT NULL,
    AmbienteTecnicas TINYINT NOT NULL,
    
    CONSTRAINT PkAmbienteProjeto PRIMARY KEY(Id),
    CONSTRAINT FkAmbienteProjeto FOREIGN KEY(IdCliente)
        REFERENCES Cliente(Id)
);

CREATE TABLE Comentario(
    Id INTEGER IDENTITY(0,1) NOT NULL,
    IdCampoTabela TINYINT NOT NULL,
    NomeTabela NVARCHAR(40) NOT NULL,
    NomeColuna NVARCHAR(40) NOT NULL,
    Comentario NVARCHAR(1024) NOT NULL,

    CONSTRAINT PkComentario PRIMARY KEY(Id)
);

**Comment by pedrohbferreira** [comment]
Banco criado com sucesso, connection string já está no web.config(login/senha ocultos)
